name: cardoctor_chatapp
description: Cardoctor chat app package for company.
version: 0.0.1
homepage: https://github.com/Danilz-2706/cardoctor_chatapp

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  video_thumbnail: ^0.5.3
  analyzer: ^5.2.0
  camera: ^0.10.5+3
  flutter_svg: 0.23.0+1
  cached_network_image: ^3.2.3
  circular_countdown_timer: 0.2.1
  dio: ^4.0.6
  ffi: 2.0.1
  file_picker: 5.2.6
  flutter_html: ^2.2.1
  flutter:
    sdk: flutter
  flutter_emoji: ^2.5.1
  flutter_screenutil: ^5.6.0
  gallery_saver: ^2.3.2
  google_fonts: ^3.0.1
  holding_gesture: 1.1.0
  # image_picker: 1.0.2
  image_picker: ^0.8.7+5
  intl: ^0.18.0
  path: ^1.8.2
  fluttertoast: ^8.1.2
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  device_info_plus: ^8.0.0
  uuid: ^3.0.7
  video_player: ^2.7.0
  wakelock: ^0.6.2
  wakelock_windows: ^0.2.1
  web_socket_channel: ^2.4.0
  wechat_assets_picker: 8.0.0
  open_filex: ^4.3.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  win32: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:


  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/
    - assets/imgs/


#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
